#!/usr/bin/env pwsh
# ───────────────────────────────────────────────────────────────
#  TrackFit Ultra — Start Script
#  Launches both the FastAPI backend and the Expo frontend
# ───────────────────────────────────────────────────────────────

$RootDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$BackendDir = Join-Path $RootDir "backend"
$FrontendDir = Join-Path $RootDir "Fitness-Implement"
$VenvPython = Join-Path $RootDir ".venv\Scripts\python.exe"

Write-Host ""
Write-Host "╔══════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║         TrackFit Ultra — Startup             ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# ─── Detect LAN IP ────────────────────────────────────────────
$lanIP = (Get-NetIPAddress -AddressFamily IPv4 |
    Where-Object { $_.InterfaceAlias -notlike "*Loopback*" -and
                   $_.IPAddress -notlike "169.*" } |
    Select-Object -First 1).IPAddress

if (-not $lanIP) { $lanIP = "localhost" }

Write-Host "📡 Your LAN IP: $lanIP" -ForegroundColor Yellow
Write-Host ""

# ─── Update frontend .env.local with current LAN IP ───────────
$envLocal = @"
# Auto-generated by start.ps1 — do not edit manually
EXPO_PUBLIC_API_URL=http://${lanIP}:8000/api/v1
EXPO_PUBLIC_DOMAIN=${lanIP}:8000
"@
Set-Content -Path (Join-Path $FrontendDir ".env.local") -Value $envLocal
Write-Host "✅ Updated .env.local → http://${lanIP}:8000/api/v1" -ForegroundColor Green
Write-Host ""

# ─── Start Backend ─────────────────────────────────────────────
Write-Host "🚀 Starting FastAPI backend on http://0.0.0.0:8000 ..." -ForegroundColor Cyan
$backendJob = Start-Job -ScriptBlock {
    param($venvPy, $dir)
    Set-Location $dir
    & $venvPy -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 2>&1
} -ArgumentList $VenvPython, $BackendDir

# Wait for backend to start
Start-Sleep -Seconds 3

# Quick health check
try {
    $health = Invoke-RestMethod "http://localhost:8000/health" -TimeoutSec 5
    Write-Host "✅ Backend is running: $($health | ConvertTo-Json -Compress)" -ForegroundColor Green
} catch {
    Write-Host "⚠️  Backend may still be starting up..." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "📱 Starting Expo frontend..." -ForegroundColor Cyan
Write-Host ""
Write-Host "─────────────────────────────────────────────────" -ForegroundColor DarkGray
Write-Host " Backend API: http://${lanIP}:8000/api/v1" -ForegroundColor White
Write-Host " API Docs:    http://localhost:8000/docs" -ForegroundColor White
Write-Host " Scan the QR code below with Expo Go to open app" -ForegroundColor White
Write-Host "─────────────────────────────────────────────────" -ForegroundColor DarkGray
Write-Host ""

# ─── Start Frontend ────────────────────────────────────────────
Set-Location $FrontendDir
& npm start

# ─── Cleanup ───────────────────────────────────────────────────
Write-Host ""
Write-Host "Stopping backend..." -ForegroundColor Yellow
Stop-Job $backendJob -ErrorAction SilentlyContinue
Remove-Job $backendJob -ErrorAction SilentlyContinue
